add distanceExcercise
tomijava/java-programs pull request #5
Opened 2018-02-17 13:46 UTC by tomijava

2018-02-17 16:25 UTC, tomaszte requested changes

2018-02-17 16:25 UTC, tomaszte commented on Distance.java
> +            /* Napisz klase ktora trzyma informacje o wartosci odleglosci i
fix intendation lines 5-70

2018-02-17 16:25 UTC, tomaszte commented on Distance.java
> +        public String toString()
fix intendation

2018-02-17 16:25 UTC, tomaszte commented on Distance.java
> +            public void changerMesure(DistanceUnitType convert) {
fix method name, and parameter name

2018-02-17 16:25 UTC, tomaszte commented on Distance.java
> +            private double cmMeasure;
cmMeasure field is redundant i think and we should avoid defining fields that we don't really need.
You could try to implement method 
int getDistanceInUnit(Distance distance, DistanceUnitType unitType);
that will return distance in different unit, but will not modify the object.
You could use that method for comparing distances and changing unit type.

2018-02-20 16:43 UTC, tomijava commented on Distance.java
> +            /* Napisz klase ktora trzyma informacje o wartosci odleglosci i
ok :(

2018-03-01 22:30 UTC, tomaszte requested changes

2018-03-01 22:30 UTC, tomaszte commented on Distance.java
> +            cmMeasure = this.distance *100000;
instead of magic number 100000 define constant named like CENTIMETERS_IN_KILOMETER

2018-03-01 22:30 UTC, tomaszte commented on Distance.java
> +	enum DistanceUnitType
spacing

2018-03-01 22:30 UTC, tomaszte commented on Distance.java
> +	/* Napisz klase ktora trzyma informacje o wartosci odleglosci i
spacing

2018-03-01 22:30 UTC, tomaszte commented on Distance.java
> +    *///wtf
remove that ///wtf 💃

2018-03-01 22:30 UTC, tomaszte commented on Distance.java
> +            cmMeasure = this.distance *100000;
do that for every 'magic number'
https://stackoverflow.com/questions/47882/what-is-a-magic-number-and-why-is-it-bad

2018-03-01 22:30 UTC, tomaszte commented on Distance.java
> +            	this.distance *= 1000;
spacing

2018-03-04 19:41 UTC, merged